services:
  website:
    build: ./website
    ports:
      - "8080:8080"
    networks:
      - app_network

  api:
    build: ./api
    ports:
      - "8000:8000"
    networks:
      - app_network
    volumes:
      - ./data:/app/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - website
      - api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
