// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $builder_index from "./routes/builder/index.tsx";
import * as $docs_index from "./routes/docs/index.ts";
import * as $docs_v1_index from "./routes/docs/v1/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $sign_up_index from "./routes/sign-up/index.tsx";
import * as $InteractiveExample from "./islands/InteractiveExample.tsx";
import * as $PrintOnLoad from "./islands/PrintOnLoad.tsx";
import * as $builder_Builder from "./islands/builder/Builder.tsx";
import * as $docs_MarkdownContent from "./islands/docs/MarkdownContent.tsx";
import * as $docs_NavigationV1 from "./islands/docs/NavigationV1.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/builder/index.tsx": $builder_index,
    "./routes/docs/index.ts": $docs_index,
    "./routes/docs/v1/index.tsx": $docs_v1_index,
    "./routes/index.tsx": $index,
    "./routes/sign-up/index.tsx": $sign_up_index,
  },
  islands: {
    "./islands/InteractiveExample.tsx": $InteractiveExample,
    "./islands/PrintOnLoad.tsx": $PrintOnLoad,
    "./islands/builder/Builder.tsx": $builder_Builder,
    "./islands/docs/MarkdownContent.tsx": $docs_MarkdownContent,
    "./islands/docs/NavigationV1.tsx": $docs_NavigationV1,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
